### PR TITLE
add C++ interface

### LINKED ISSUE #36: Support C++ version
SXG generator in C++ may be convenient.

### PR DESCRIPTION
**Pull request by kumagi**
close #36

### CODE REVIEW

**Comment by gaul** [comment]
Could you share the motivation and intent of this change?  Does it replace or supplement the existing C code?  If the latter, should it be some minimal wrapper for the C calls?  Also is it possible to break this into something smaller than a single 2,000 line change, e.g., formatting in one PR, remove C99 structure initializers in another, etc.?

**Comment by kumagi** [comment]
The motivation is making node.js wrapper for SXG. C++ wrapper is suitable for that purpose.
But 2000+ lines modification is hard to understand, I'll split it into "C modification" and "appending C++" code.

**Comment by gaul** [comment]
Does node.js integrate more cleanly with node.js?  If so maybe we should mention this in the related issue?  Also it seems like there is now duplicated C and C++ code paths.  Instead one should just wrap the other and marshal parameters/error codes as needed.

**Comment by twifkak** [comment]
Closing since I suspect this is too hard to integrate into the existing code now. Please reopen if you think otherwise.

**Pull request closed without merging**
