### PR TITLE
Purge package related things

### PR DESCRIPTION
**Pull request by kumagi**
Debian folk suggested me to make packaging stuff separate from source code tarball.
It simplify the procedure of packaging.
Purged part will become another independent branch of this repository.

### CODE REVIEW

**Comment by kumagi** [comment]
Blocked by https://github.com/google/libsxg/pull/21 I'll reopen after that.

**Comment by kumagi** [comment]
purged stuffs become another independent branch https://github.com/google/libsxg/tree/debian
it is a sort of best practice on packaging for debian.

**Comment by gaul** [comment]
Is the intent that the package branch will become a long-lived one that will periodically rebase onto master?

**Comment by kumagi** [comment]
@gaul `debian` branch does not rebase onto master. It becomes independent from main tree.
Because library versioning and package versioning is independent in debian convention.

**Comment by kumagi** [comment]
Yes, it looks like gh-pages.

**Pull request merged**
